# Site settings
name: Hung T Nguyen 
email: hungn2@stanford.edu 
canonical_url: https://hnguyen094.github.io 
keywords: "Software Engineer, Game Developer, Cyber Security"
skills: "Software Engineer Intern in Sunnyvale, CA"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/hung-the-nguyen/
  - title: github 
    url: https://github.com/hnguyen094
  - title: medium
    url: https://medium.com/@hungnguyen094
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
